version: "3.9"
services:
  meilisearch:
    image: getmeili/meilisearch:v1.2.0
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    volumes:
      - type: bind
        source: ./meili_data
        target: /meili_data
